---
env:
    name: &env_name BipedalWalker-v3
    n_workers: 1
    n_envs: &nenvs 64
    seed: 0
    precision: &prec 32

model:
    encoder: 
        units_list: []
        activation: relu
    actor:
        units_list: [64, 64]
        init_std: 1
        norm: null
        kernel_initializer: orthogonal
        activation: tanh
    value:
        units_list: [64, 64]
        norm: null
        kernel_initializer: glorot_uniform
        activation: tanh

agent:
    algorithm: &algo ppo
    precision: *prec
    gamma: &gamma .99

    MAX_STEPS: 1e10
    N_STEPS: &nsteps 256
    N_EPOCHS: &nepochs 4
    N_MBS: &nmbs 4
    LOG_PERIOD: 200
    EVAL_PERIOD: 200
    max_kl: 0            # early stop when max_kl is violated. 0 or null suggests unbound

    normalize_obs: True
    normalize_reward: True

    # model path: root_dir/model_name/models
    # tensorboard path: root_dir/model_name/logs
    # the following names are just examples; they will be reset in our training process
    root_dir: *algo                         # root path for tensorboard logs
    model_name: *algo
    RECORD: False

    # arguments for optimizer
    opt_name: adam
    schedule_lr: False
    lr: 3e-4
    clip_norm: .5
    opt_kwargs:
        epsilon: 1.e-5
    # arguments for loss
    clip_range: .2          # clip range for ppo
    entropy_coef: .0
    value_coef: 1

buffer:
    adv_type: gae     # nae or gae
    precision: *prec
    gamma: *gamma
    lam: .95
    n_envs: *nenvs
    N_STEPS: *nsteps
    N_EPOCHS: *nepochs
    N_MBS: *nmbs        # number of minibatches
    # mini-batch size = n_workers * n_envs * epslen / n_mbs
